### ISSUE TITLE
Support for moving to bookmarked subsections with screen reader

### ISSUE THREAD

**Issue by nvdaes** [readium/readium-desktop#1003]
Tested with NVDA 2019.3.1 on Windows 7 with Thorium 1.1.1.

STR:
1. Press h several times to move to subsections of a chapter.
2. Press control+b to add different bookmarks.
3. press control+n, select bookmarks and then try to move to a specific bookmark.

Actual:
The cursor can be moved to specific chapters, not subsections.

Expected:
The cursor should be located in the specific subsection of the chapter.

**Comment by danielweck** [comment]
I successfully tested NVDA on Windows 10 with the typical usage scenario you describe (not just bookmarks, but also any navigated publication hyperlink, such as table of contents, page number, landmarks, etc.).

However, if I remember correctly, this only works reliably when using a recent version of Windows 10 (i.e. not an older patch / update release, let alone Windows 7).

Note that VoiceOver doesn't actually work as well as NVDA does in this usage scenario, which is why a special tabbable link is injected in HTML documents immediately at the beginning, so that keyboard-tabbing from outside the content frame into the actual content affords immediate access to the targeted hyperlink destination.

In order words, this initial top-level link is similar to a "skip link" which is commonly found on website, to "skip to main content" (except here, the link destination is whatever the user intends to navigate to, based on the chosen TOC heading, or boookmark, or page break, etc.).

Note that we had a discussion with NVDA lead developers about creating DOM selections, which unfortunately does not work yet in NVDA (unlike VoiceOver). DOM selections ; as opposed to text / clipboard selections in the screen reader's own virtual buffer ; are necessary in Thorium / `readium-desktop` to reference precise text in HTML documents, and to store these locations as bookmarks. Failing that, the other option is to emulate a mouse click on a particular HTML element, such as a paragraph of interest. Failing that, by default bookmarks are created based on the visible HTML content in the top-left corner of the page spread or scrolling viewport.

**Comment by danielweck** [comment]
So, could you please try to use the special top-level link injected in HTML documents by keyboard-tabbing into the content frame? Please let me know if your screen reader is able to announce the presence of this "skip link", and please check whether the link destination is the intended location. I suggest testing with TOC table of contents headings first, as these are reliable HTML element fragment identifiers.

For bookmarks, the problem is that the screen reader's TTS narration based on its virtual buffer does not synchronize the scrolling position of the paginated flow, or scrolling viewport. As a result, the screen reader announces text from EPUB content documents that is potentially not visible on the screen, and the screen reader emits no perceivable events (from the DOM perspective) which could be used to infer its reading position (i.e. some location in the HTML document). Therefore, hitting CTRL-B to create bookmarks takes into account the content in the visible viewport, not the screen reader's playback progress ... unless of course mouse click or text selection is created prior to hitting CTRL-B, but this seems impossible with NVDA.

PS: regarding text selection, one possibility is to make the entire HTML document an editable flow of text, which would trigger a special screen reader mode whereby the character-level cursor becomes accessible, and creating selections is enabled. Unfortunately this would totally break a ton of other things, so it is not a realistic solution.

**Comment by nvdaes** [comment]
@danielweck , bookmarks and table of contents links work both well with NVDA on Win 7 and 10. Also moving to pages was working, and this works also on Windows 7, thanks"
The problem is that I needed an explanation, may not be intuitive. I think we should provide some kind of translated documentation or a short user guide.

**Comment by nvdaes** [comment]
Though this works perfectly for TOC and also for bookmarks, the presence of the link is announced, but the label should be more meaningful, since NVDA says just frame link. A documented accesskey, tab or another one, could be also useful.

**Comment by nvdaes** [comment]
I will close this for now since this works.
