### ISSUE TITLE
window.alert() in EPUB HTML content documents => modal popup for BrowserWindow (reader view)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#121]
This is just a question: should we disable / handle `window.alert()` requests?

**Comment by JayPanoz** [comment]
They’re also `window.prompt()` and `window.confirm()`. 

When I first saw this issue I could not find any authoring use case for those ones, excepted using `window.alert()` to debug things – [there’s even an example](https://books.google.fr/books?id=7aiQLT_0dsgC&pg=PA194&lpg=PA194&dq=EPUB3+best+practices+navigator.epubReadingSystem&source=bl&ots=yMdhZu5WhP&sig=6CqlMB2122qbHvhQoOGyqdlpZYM&hl=en&sa=X&ved=0ahUKEwjG-evzt_XZAhVELFAKHW9pBiwQ6AEIKzAA#v=onepage&q=EPUB3%20best%20practices%20navigator.epubReadingSystem&f=false) related to `navigator.epubReadingSystem` in the *EPUB3 Best Practices* book for instance. 

But thinking about this + `localStorage`. If a publisher is willing to provide users with a “reset/clear storage” option, it would be reasonable to think `window.confirm()` could be one way to alert the user and get a confirmation for instance. 

Now, I really can’t tell if that’s being currently used in any book, and of course there is the concern that it’s often used for malicious things on the web (scam/malware/etc.). [Google now recommends developers to use `dialog` for user input for instance](https://developers.google.com/web/updates/2017/03/dialogs-policy), because of the malice.

**Comment by clebeaupin** [comment]
We never use window.alert. 
The only dialog boxes you can see as a window.alert are fired when the main process crashes.
This is a default electron behaviour.

**Comment by danielweck** [comment]
"in EPUB HTML content documents" ;)

**Comment by danielweck** [comment]
Side-loaded content (i.e. third-party publications) should not be capable of blocking the Electron entire renderer thread (the entire `BrowserWindow` is captured, not just the embedded `iframe`/`webview`!).

I fixed this issue in `r2-navigator-js` by leveraging the `preload` script timing/privilege to replace the built-in `window.alert|confirm|prompt` Electron implementations, specifically inside the `webview` window context that hosts EPUB content documents. The modal, thread-blocking dialogs are simply replaced with `console` logging.

Another option would have been to use Electron's own `dialog` implementation, or some other third-party offering. However I think this would be a waste of our precious developer time, because frankly I think that interactive publications should not rely on modal popup dialogs ... and anyway I have never actually seen ones that do ;) (apart from test / sample EPUBs)
