### ISSUE TITLE
cloned project and it fails to build with npm start

### ISSUE THREAD

**Issue by darrenahunter** [readium/readium-desktop#151]
it appears the required module ta-json is not included in the package.json

running npm install --save ta-json fixes the issue

thanks

**Comment by danielweck** [comment]
I have not encountered this problem at my end, even after a good cleanup: `rm -rf ./node_modules/ && npm install && npm run __postinstall` (assuming `package-lock.json` is untouched after the `git clone`)

What version of NodeJS and NPM are you using? What Git revision of `readium-desktop`? Thanks!

**Comment by darrenahunter** [comment]
hi daniel thanks for reply
I am using npm 6.0.1 and node 8.9.4
I cloned the master branch and ran npm install then npm start
it failed missing ta-json
on checking package.json I couldn't see ta-json so npm installed it with -save
then npm start was fine - the project is up and running fine for me now
I'm not sure about the package-lock.json but when I opened the project in vscode I could see on the git tab that one file had changed and it was package-lock.json
anything else I can do to help - happy too.
not sure why ta-json wasn't in the package.json (and I don't fully understand package-lock.json)
thanks

**Comment by clebeaupin** [comment]
The key is to remove the package-lock.json. Depending of your system, npm is not working well with package-lock.json.
`rm -rf ./package-lock.json && rm -rf ./node_modules && npm install`

**Comment by Crash--** [comment]
I ran into the same issue with npm 5.6.0 and node 8.11.2.

Deleting package-lock seems to do the trick

**Comment by danielweck** [comment]
This is fixed in this PR: https://github.com/readium/readium-desktop/pull/161
(`ta-json` is an app-level dependency, but also a sub-project dep ... depending on how NPM installs packages inside `node_modules`, this was failing)
Note that I personally have issues with NPM 6+ in Windows and Linux (fine on MacOS), so I use `npm ci` instead of `npm install` for running tests (I use the command line `npm ci || npm install` to automatically switch depending on the availability of `npm ci`). Or if I need to incrementally make changes to the contents of `node_modules`, I make sure to use NPM 5.x

**Comment by danielweck** [comment]
PS: `package-lock.json` is super important (frozen, exact versions of dependencies) and it should *always* work in any buildable branch. For example, the TravisCI setup script (YAML) utilizes `npm ci` instead of `npm install` to create a strict tree of dependencies in `node_modules`.

**Comment by llemeurfr** [comment]
Seems solved.
