### ISSUE TITLE
Paginated mode by default

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#213]
The default mode must be paginated, not scrolled.

**Comment by JayPanoz** [comment]
Adding my short answer to this question during the call yesterday: 

In ReadiumCSS, the default mode is indeed paginated, but that’s purely convention – in the Western World, for trade/global publishing. 

That’s to say It’s not an opinionated choice, it’s the default mode because it is the default. 

* * *

**Further details and developments.**

I must monitor a huge amount of apps – something like 35–40 – for updates, and do partial (all those apps) or complete (add another 10–15 to the list) rounds of testing for code changes in one project. The two apps scrolling by default are clearly outliers in this set, but I can also understand why they may be scrolling by default. 

First one is made in China, and I believe you’ll find more apps with scroll by default in a set of apps targeting the Chinese market; I don’t have enough data though, esp. as it can be really really tough to navigate those apps as a Westerner who doesn’t speak nor read Mandarin Chinese. 

Second one is targeting the education market, and its User Interface is completely different than what the average (e)book reader is used to. On desktop, every tool/panel/etc. is displayed (the user can’t even hide it), probably because the UX is more about “research as work” than “reading as a hobby.” Mobile apps could also be considered simple, as if they were companion apps you can check on the go – but not use to work. 

This second one is an educated guess though, but it rang some bells two weeks ago during a project defence jury. I must admit that, in retrospect, I kinda deeply regret you were not on this jury, Laurent, since those two hours were quite probably the ultimate redux of the issues they’ve been encountering with digital publishing for the last 5–6 years in this higher-education context e.g. research vs reading, non-linear vs linear, use cases, distribution, formats (EPUB vs website vs both), business models, etc. That was monumental feedback.

I’m not sure a recap would do projects, their presentation, and conversations that followed, justice but I can try if you want – not sure when I’ll be able to deliver it though but probably late at night.

**Comment by danielweck** [comment]
Because `r2-testapp-js` is a ... "test app", ReadiumCSS is turned off by default, then once it is turned on, scroll is the default view mode, so column-based pagination must be activated explicitly.

**Comment by llemeurfr** [comment]
The modification has been made to the app. 

I agree that choosing paginated as a default mode is a pure convention. I personally think it's the best approach for desktop apps (because of a large screen, spreads are useful). My personal opinion is different for  mobile apps.
