### ISSUE TITLE
catalog - add feed text input (URL): should have submit button to accept typed-in tag (currently only press enter)

### ISSUE THREAD

**Issue by danielweck** [readium/readium-desktop#345]
Similar UX issue to https://github.com/readium/readium-desktop/issues/344

**Comment by llemeurfr** [comment]
This issue is about the addition of an OPDS feed in the Catalog view (not a tag in the Book Info view). 

I agree that the current UX is not great: the user enters a URL, has to select enter, this opens a dialog box, he enters a catalog name and can modify the URL, he selects "Add" (or "Back". 

Let's fully use the dialog box. the new behavior is:
"Add a feed" becomes a button named "Add an OPDS feed" (I think it's good to see the term OPDS somewhere). The input field is suppressed. Selecting this button opens the dialog box. The name and URL are entered in this form. 

Be careful to update the labels accordingly please.

**Comment by Scarsniik** [comment]
Fixede in #550
