### ISSUE TITLE
Get some padding in focused labels (in focus rings)

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#573]
On some labels, the first and last letter is “cut’ by the focus ring (i.e. blue line around the focused item). This is especially the case for “skip to context” (before it is moved, which is another open issue). It is NOT the case for labels already in “boxes” (e.g. All Books”).  

Outline-offset seems to be the proper CSS trick to use when needed. 
https://css-tricks.com/almanac/properties/o/outline-offset/

**Comment by Scarsniik** [comment]
Fixed by #637

**Comment by danielweck** [comment]
@llemeurfr in some (many) cases, `outline-offset` introduces clipping due to the visual constraints of the containing CSS box. Thus the `+2` / `-2` outline pixels:
https://github.com/readium/readium-desktop/blob/cf8be49c29afea718fb3db4c78a4f4d485368065/src/renderer/assets/styles/focus-mixin.css#L4-L5

@Scarsniik 's fix introduces padding in affected GUI components (e.g. buttons), which provides additional room for the aforementioned outline technique.
