### ISSUE TITLE
Support MathML via MathJax

### ISSUE THREAD

**Issue by llemeurfr** [readium/readium-desktop#643]

**Comment by danielweck** [comment]
Sample EPUB3 publication "linear algebra":
https://idpf.github.io/epub3-samples/30/samples.html#linear-algebra

**Comment by danielweck** [comment]
Note that this issue is labelled with "accessibility", but in fact the version of Chromium used in the (old) version of Electron currently used by `readium-desktop` does not support presentational MathML at all (as demonstrated in the screenshot below). That being said, as far as I know MathML support has not improved significantly in recent Electron/Chromium releases, so MathJax is very much needed for visual consistency.

![ThoriumMathML](https://user-images.githubusercontent.com/625201/63895559-5b6cdc00-c9e7-11e9-923c-5a0feba2e6f2.png)

**Comment by danielweck** [comment]
Note that speech output support can be experimented with using this code:
https://github.com/pkra/mathjax-node-sre

**Comment by danielweck** [comment]
WIP PR: https://github.com/readium/readium-desktop/pull/644
