### ISSUE TITLE
Problems with styling

### ISSUE THREAD

**Issue by gregoriopellegrino** [readium/readium-desktop#809]
Hi,
on Mac v 1.6.0-rc.0 I noticed that some styles are not respected (e.g. centered text).

If necessary, I can pass the EPUB file privately.

Here is the difference in graphical rendering with Thorium, ADE and iBooks.

<img width="1503" alt="Schermata 2019-10-22 alle 16 01 14" src="https://user-images.githubusercontent.com/5065125/67293865-5313b780-f4e5-11e9-8811-b317c2396aba.png">
<img width="1552" alt="Schermata 2019-10-22 alle 16 01 34" src="https://user-images.githubusercontent.com/5065125/67293871-55761180-f4e5-11e9-91a6-d1c75c078bdb.png">
<img width="1552" alt="Schermata 2019-10-22 alle 16 01 50" src="https://user-images.githubusercontent.com/5065125/67293878-57d86b80-f4e5-11e9-9999-885ee6e46f28.png">

**Comment by danielweck** [comment]
I think this is a bug in Thorium (i.e. not ReadiumCSS).

We currently only expose `textAlignEnum.left` and `textAlignEnum.justify` in the display settings UI. There is also `textAlignEnum.right` and `textAlignEnum.start`. I think we should replace `textAlignEnum.left` with `textAlignEnum.start`, which will be supported in Chromium (automatic RTL switch). That being said, in order to achieve "center" we need to leave the publisher's style alone, which means we need an "auto" value in the radio buttons options (to reset to `undefined`).

`readium-desktop` code:
https://github.com/readium/readium-desktop/blob/7f846368c1945e4ec3c995d8afcce1cf1e644cd5/src/renderer/components/reader/ReaderOptions.tsx#L237-L273

ReadiumCSS references:
https://github.com/readium/readium-css/blob/develop/docs/ReadiumCSS-user_variables.css#L16
https://github.com/readium/readium-css/blob/develop/docs/CSS12-user_prefs.md#text-align
https://github.com/readium/readium-css/blob/develop/docs/CSS19-api.md#user-settings

Note that the `r2-navigator-js` default is `start` (perhaps it should be `undefined`?):
https://github.com/readium/r2-navigator-js/blob/e9ce56316b102bfe0a295cf0e05f8b11c6d40029/src/electron/common/readium-css-settings.ts#L136

**Comment by danielweck** [comment]
Could you please send me the EPUB via email, so I can reproduce the bug and implement a fix? Thanks!

**Comment by JayPanoz** [comment]
@danielweck Ah yeah, you probably want to remove the CSS variable (a.k.a. custom property) on the root element in that case, to make sure it doesn’t even resolve to the default if the value is not supported. 

> I think we should replace textAlignEnum.left with textAlignEnum.start, which will be supported in Chromium (automatic RTL switch).

That’s a +1 from me as this will make it a lot easier for RTL and [support is becoming great](https://caniuse.com/#feat=mdn-css_properties_text-align_flow_relative_values_start_and_end) – there’s been progress on that side lately, and [CSS logical properties](https://caniuse.com/#feat=css-logical-props) have had tremendous momentum.

**Comment by danielweck** [comment]
Fixed.

Build in progress ...
https://travis-ci.org/readium/readium-desktop/builds/601467061

... will be uploaded here:
https://github.com/readium/readium-desktop/releases
