### ISSUE TITLE
Requested feature: code inspector

### ISSUE THREAD

**Issue by gregoriopellegrino** [readium/readium-desktop#810]
It would be very useful to debug graphic and typographical problems

**Comment by danielweck** [comment]
Allowing the "web inspector" / content debugger would indeed be very useful for publication creators / QA people, etc.
However, I think enabling this feature would be problematic in the official builds of Thorium, because of LCP DRM.
That being said. this would not be a concern with the prerelease builds of Thorium which do not support DRM.

**Comment by danielweck** [comment]
Build in progress:
https://travis-ci.org/readium/readium-desktop/builds/601448282

Once this is done, the updated prerelease / test app installers will appear here:
https://github.com/readium/readium-desktop/releases

These "test" builds of Thorium do not support LCP DRM, they use the developer-mode database backend (in other words, the bookshelf, settings, etc. do not overlap a regular "stable" Thorium installation), and they have an additional menu entry to debug EPUB content.
