### ISSUE TITLE
Top menu bar is not translated

### ISSUE THREAD

**Issue by probonopd** [readium/readium-desktop#818]
Top menu bar is not translated when a language other than English is selected. The HTML content is correctly switched to the selected language but the top-level menu stays English, even after a restart of the application.

![menu](https://user-images.githubusercontent.com/2480569/67359431-bd167600-f552-11e9-9c0f-9b20a65a1546.png)

This is on Ubuntu 18.04.2 LTS using `thorium-1.0.6-rc.0.AppImage`.

**Comment by danielweck** [comment]
Thank you for reporting!

So, for MacOS, we are aware that not all menu entries are translated as per the user-chosen language in the application, instead the default operating system strings / locale are used:
https://github.com/readium/readium-desktop/blob/ee9ee8ca1f4dc23d87eb3b9352390f55fa8ef8cf/src/main/menu.ts#L147-L245

For Windows / Linux, the situation is different, because the top menu is explicitly removed / void for all created Electron windows (unlike MacOS where an app must have a common top menu for all created windows):
https://github.com/readium/readium-desktop/blob/ee9ee8ca1f4dc23d87eb3b9352390f55fa8ef8cf/src/main/menu.ts#L135-L145

There are however two exceptions, as indicated by the `if (IS_DEV || (isReaderView && _CONTINUOUS_INTEGRATION_DEPLOY))` conditional statement in the above code snippets:
1) development mode (`npm run start:dev` from a local copy of the source code)
2) test / prerelease builds deployed via continuous integration from the `develop` branch ( https://github.com/readium/readium-desktop/releases )

To conclude, based on your screenshot, it looks like `win.setMenu(null);` on Linux does not always work. We will have to test this using a stable build, because the current test / prerelease builds actually create a top menu with one entry (`EPUB DEBUG` > `OPEN WEB INSPECTOR / DEVELOPER TOOLS`)  so that early adopters / testers / experimenters can use DRM-free builds of Thorium to QA / inspect / debug EPUB publications.
https://github.com/readium/readium-desktop/blob/ee9ee8ca1f4dc23d87eb3b9352390f55fa8ef8cf/src/main/menu.ts#L26-L44

**Comment by danielweck** [comment]
This was fixed a while ago, sorry I do not have the exact commit.
