### ISSUE TITLE
Thorium (MacOS Catalina) - Cannot turn pages in full screen mode

### ISSUE THREAD

**Issue by wareid** [readium/readium-desktop#904]
Version: v.1.1.1
MacOS: Catalina (10.15.2)

I found an issue in the desktop MacOS app where if I go into full-screen mode when reading an EPUB I cannot turn the pages to the next page in paginated mode or to the next chapter in scrollable mode.

**Comment by danielweck** [comment]
Thanks for reporting @wareid 

I am able to "turn pages" using the left/right arrow keys, but only after initially placing/forcing the keyboard focus on either the EPUB text (publication rendering viewport) or the application "chrome" (UI controls, such as the top bar), using a mouse click, or via a keyboard tab.

I suspect that when activating fullscreen mode, keyboard focus is "undefined" due to the fullscreen toggle button having switched state. I will investigate.

**Comment by danielweck** [comment]
My personal preference for Thorium's fullscreen "distraction-free" mode would be to include actual previous/next UI buttons that reveal themselves upon mouse hover or touch interaction. The page-turn command in fullscreen mode should not be accessible only with left/right arrow keys, instead Thorium should also be controllable with a keyboard-less setup (e.g. "kiosk" touchscreeen).

**Comment by danielweck** [comment]
Fixed via https://github.com/readium/readium-desktop/commit/53bc0c8289a3a95a0d6e33da47687c1fcf014037
