### ISSUE TITLE
Missing space after Publisher, Language on Information dialog

### ISSUE THREAD

**Issue by ways2read** [readium/readium-desktop#960]
In the section *More Info* there is space between 'Publisher' and the name of the publisher, but not with Language and Identifier, which are concatenated with their respective field values.
Screenshot below:
![image](https://user-images.githubusercontent.com/9092859/75242803-9b85ff00-577d-11ea-9551-2cde318c3b1a.png)

**Comment by danielweck** [comment]
Thank you for reporting. This problem was fixed in the `develop` branch some time ago. The fix can be tested using the automated "pre-release" builds available from this GitHub link:
https://github.com/readium/readium-desktop/releases

**Comment by danielweck** [comment]
Indeed, the identifier is now missing (thank you for pointing this out, Richard!). I am investigating ...

Note that your bug report prompted me to fix a few other issues related to metadata formatting / display:
https://github.com/readium/readium-desktop/compare/36fbca41c4307b4a0703164cd9873bc7364d47ea...7ed4e1eade6e0a0f68e9445e50736db54270148a

**Comment by danielweck** [comment]
The publication identifier metadata was removed in this Pull Request:
https://github.com/readium/readium-desktop/pull/881

@llemeurfr I seem to remember that you advocated for the removal of the publication unique identifier (ISBN or otherwise) in the information / metadata popup dialog, but I cannot find a record of related conversations / decisions. Sorry if I am being wrong :)

Personally, I feel that even though the unique publication identifier is likely irrelevant / useless to most (human) readers, it *may* be important to some people, for some usage scenarios. So I would be in favour of re-instating it.

**Comment by danielweck** [comment]
I created a Pull Request to discuss this further: https://github.com/readium/readium-desktop/pull/961
